[package]
name = "hash-tree-crypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
debug_print = "1.0.0"
rpassword = "7.0.0"