[package]
name = "hash-tree-crypt"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
chrono = "0.4.33"
clap = "4.5.0"
env_logger = "0.11.1"
log = "0.4.20"
rpassword = "7.0.0"
